# Generated by Django 4.2.26 on 2025-12-03 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('iso2', models.CharField(max_length=2, unique=True)),
                ('iso3', models.CharField(max_length=3, unique=True)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('boundary', models.JSONField(blank=True, help_text='GeoJSON geometry', null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EnergyDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('dataset_type', models.CharField(choices=[('resource', 'Resource Potential'), ('climate', 'Climate'), ('phes', 'PHES Sites')], max_length=24)),
                ('source', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True)),
                ('file_name', models.CharField(blank=True, max_length=256)),
                ('file_checksum', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('level', models.CharField(blank=True, max_length=64)),
                ('boundary', models.JSONField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='core.country')),
            ],
            options={
                'ordering': ['country__name', 'name'],
                'unique_together': {('country', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ResourceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_type', models.CharField(choices=[('solar', 'Solar'), ('wind', 'Wind'), ('hydro', 'Hydro'), ('biomass', 'Biomass'), ('other', 'Other')], max_length=16)),
                ('metric', models.CharField(max_length=64)),
                ('value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit', models.CharField(default='', max_length=32)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_metrics', to='core.country')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.energydataset')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_metrics', to='core.region')),
            ],
            options={
                'ordering': ['resource_type', 'country__name', 'metric'],
            },
        ),
        migrations.CreateModel(
            name='HydroSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('elevation_m', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('head_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('storage_capacity_mwh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('turbine_capacity_mw', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('identified', 'Identified'), ('study', 'Feasibility Study'), ('construction', 'Under Construction'), ('operational', 'Operational')], default='identified', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hydro_sites', to='core.country')),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hydro_sites', to='core.energydataset')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hydro_sites', to='core.region')),
            ],
            options={
                'ordering': ['country__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClimateSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variable', models.CharField(max_length=64)),
                ('unit', models.CharField(max_length=32)),
                ('statistics', models.JSONField(blank=True, default=dict, help_text='Precomputed indicators (mean, p90, etc.)')),
                ('series', models.JSONField(blank=True, default=list, help_text='Serialized time series data')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_series', to='core.country')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_series', to='core.energydataset')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='climate_series', to='core.region')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='climate_series', to='core.hydrosite')),
            ],
            options={
                'ordering': ['variable', 'country__name'],
            },
        ),
    ]
