# Generated by Django 4.2.26 on 2025-12-03 14:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('document', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('data', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='energydataset',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='hydrosite',
            name='head_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='hydrosite',
            name='storage_capacity_mwh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='hydrosite',
            name='turbine_capacity_mw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='resourcemetric',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='climateseries',
            constraint=models.UniqueConstraint(fields=('dataset', 'country', 'region', 'site', 'variable'), name='unique_climate_series'),
        ),
        migrations.AddConstraint(
            model_name='hydrosite',
            constraint=models.UniqueConstraint(fields=('country', 'name'), name='unique_site_per_country'),
        ),
        migrations.AddConstraint(
            model_name='resourcemetric',
            constraint=models.UniqueConstraint(fields=('dataset', 'country', 'resource_type', 'metric', 'year'), name='unique_metric_per_scope'),
        ),
        migrations.AddField(
            model_name='reportattachment',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.hydrosite'),
        ),
    ]
